import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../common/styles/globals.css'

import Header from '../common/components/header'

const geistSans = localFont({
  src: '../common/fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: '../common/fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className="container mx-auto">{children}</div>
      </body>
    </html>
  )
}
